package com.example.tinkoffbot.bot;

public enum BotState {
    START,
    SHOW_MAIN_MENU,
    FILLING_NEW_DATA,
    ASK_FIRST_NAME,
    ASK_LAST_NAME,
    ASK_SOME_NEW_DATA,
    ASK_IF_DATA_TYPED_PROPERLY, //show yes no panel
    FILLED_NEW_DATA,
    SENDING_DATA_ERROR_REPORT,
    ASK_NUMBER_OF_WRONG_DATA,
    ASK_TO_PROPER_DATA, // might be split
    ASK_IF_NEW_DATA_IS_PROPER, //show yes no panel
    SEND_DATA_REPORT,
    COLLECTING_USER_STATISTICS,
    SHOW_PERIOD_VARIANTS, //day, week, month, whole time
    SENDING_USER_STATISTICS,
    SEND_REPLY_ON_HELP,
    SHOW_GROUP_LEAD_PANEL,
    GROUP_STATISTIC_COLLECT,
    ANALYSING_DATA_REPORTS,
    SOMETHING_ELSE,
    SEND_REPLY_ON_GROUP_HELP,
    BACK_TO_MAIN_MENU
}
