package com.example.tinkoffbot.bot;

public enum BotState {
    START,

    SHOW_KEYBOARD_MAIN_MENU,
    SHOW_KEYBOARD_GROUP_LEAD,
    SHOW_KEYBOARD_YES_NO, //show yes no panel
    SHOW_KEYBOARD_PERIOD_VARIANTS, //day, week, month, whole time

    FILLING_NEW_DATA,
    ASK_FIRST_NAME,
    ASK_LAST_NAME,
    ASK_SOME_NEW_DATA,
    FILLING_NEW_DATA_COMPLETE,

    REPORT_FILLING_DATA_ERROR,
    ASK_NUMBER_OF_WRONG_DATA,
    ASK_TO_PROPER_DATA, // might be split
    ASK_IF_NEW_DATA_IS_PROPER, //show yes no panel
    REPORT_FILLING_DATA_ERROR_COMPLETE,

    COLLECTING_USER_STATISTICS,
    COLLECTING_USER_STATISTICS_COMPLETE,

    SEND_HELP_MESSAGE_ASSISTANT,
    SEND_HELP_MESSAGE_GROUP_LEAD,

    COLLECTING_GROUP_STATISTICS,

    ANALYSING_DATA_REPORTS,

    SOMETHING_ELSE,

    BACK_TO_MAIN_MENU
}
